name: build
on: push

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: More disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          df -h

      - name: Restart docker daemon with experimental feature
        run: |
          tmp=$(mktemp)
          sudo jq '.+{experimental:true}' /etc/docker/daemon.json > "$tmp"
          sudo mv "$tmp" /etc/docker/daemon.json
          sudo systemctl restart docker.service

      - name: Build and push
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password "${{ secrets.DOCKER_PASSWORD }}"
          TZ="Asia/Shanghai"
          tag=$(date +'%Y.%m.%d')
          #docker build --rm --no-cache --squash -t lanfanb/siqbase:tools.$tag -f Dockerfile.centos .
          #docker run --name pod -d lanfanb/siqbase:tools.$tag
          #docker cp pod:/artifacts.tar.xz artifacts.tar.xz
          #docker stop pod
          touch artifacts.tar.xz

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts.tar.xz

